slices:
    slice_boarders: 
        vcp: [3, 3.5, 4.5]
        non_vcp: [3, 3.5, 4, 4.3, 4.7, 5, 6]
    underflow: True
    overflow: True
vcp:
    data_columns:
        thickness_column: 'Board Thickness (mm)'
        spray_column: 'Pattern Plating_Spray Frequency|Copper (HZ)'
        constraints:
            current_pattern:
                lower: 17
                upper: 21
        fit_parameters:
            - time_column
            - current_density_column
            - thickness_column
            - spray_column
    calculation_model: board_linear_calculation
    fit_model: 'linear_board_and_spray'
    start_values: [0.1, 1, 1, 1]
non_vcp:
    data_columns:
        thickness_column: 'Board Thickness (mm)'
        constraints:
            current_pattern:
                lower: 17
                upper: 21
        fit_parameters:
            - time_column
            - current_density_column
            - thickness_column
    calculation_model: board_linear_calculation
    fit_model: 'linear_board'
    start_values: [0.1, 1, 1]
errormodel: gaussian
nan_value: nan