slices:
    slice_boarders: 
        vcp: [3, 3.5, 4.5]
        non_vcp: [3, 3.5, 4, 4.3, 4.7, 5, 6]
    underflow: True
    overflow: True
vcp:
    data_columns:
        board_thickness: 'Board Thickness (mm)'
        spray_frequency: 'Pattern Plating_Spray Frequency|Copper (HZ)'
        target: minimal_thickness
        current_density: 'Pattern Plating_Copper Current Density'
        plating_time: 'Pattern Plating_Copper Plating Time (min)'
        constraints:
            current_density:
                lower: 15
                upper: 40
            spray_frequency:
                lower: 30
                upper: 70
            plating_time:
                lower: 15
        fit_parameters:
            - plating_time
            - current_density
            - board_thickness
            - spray_frequency
    calculation_model: board_linear_calculation
    fit_model: 'linear_board_and_spray'
    start_values: [0.1, 1, 1, 1]
non_vcp:
    data_columns:
        board_thickness: 'Board Thickness (mm)'
        target: minimal_thickness
        current_density: 'Pattern Plating_Copper Current Density'
        plating_time: 'Pattern Plating_Copper Plating Time (min)'
        constraints:
            current_density:
                lower: 5
                upper: 36
            plating_time:
                lower: 15
        fit_parameters:
            - plating_time
            - current_density
            - board_thickness
    calculation_model: board_linear_calculation
    fit_model: 'linear_board'
    start_values: [0.1, 1, 1]
errormodel: gaussian
nan_value: nan
